name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * SAT"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on main & workflow file is edited
  push: 
    branches: ["main"]
    paths: [".github/workflows/metrics.yml"]
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: iahmadgad.metrics.svg
          base: header, repositories, metadata
          plugin_lines: yes
          committer_branch: metrics
          token: ${{ secrets.METRICS_TOKEN }}

      - name: GitHub Metrics (Right)
        uses: lowlighter/metrics@latest
        with:
          filename: iahmadgad-right.metrics.svg
          base: ""
          plugin_followup: yes
          plugin_followup_sections: user, repositories
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 4
          plugin_languages_details: lines, bytes-size, percentage
          committer_branch: metrics
          token: ${{ secrets.METRICS_TOKEN }}
