name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_topics_limit: 50
          plugin_topics_mode: icons
          plugin_gists: yes
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          config_order: base.header, isocalendar, languages, topics, gists, leetcode
